implicitDependencies:
  - common

targets:
  lint: {}

  version:
    options:
      commitMessageFormat: >
        release(${projectName}): ${version}
      postTargets:
        - nest:publish-npm
        - nest:publish-github
  publish-npm:
    options:
      distFolderPath: packages/nest
  publish-github:
    options:
      tag: ${tag}
      notesStartTag: ${previousTag}
