logFilters:
  # discard skipped build script messages.
  # You think we'd know that since we went through the trouble explicitly disabling the package.
  - { code: YN0005, level: discard }

nodeLinker: node-modules

packageExtensions:
  "@nestjs/schematics@*":
    peerDependenciesMeta:
      typescript: { optional: true }
  "@nrwl/devkit@*":
    peerDependenciesMeta:
      nx: { optional: true }
  "@phenomnomnominal/tsquery@*":
    peerDependenciesMeta:
      # Not really, but it satisfies yarn the easiest and ofc we have typescript
      typescript: { optional: true }
  "ngx-deploy-npm@*":
    peerDependenciesMeta:
      # Only needed for init generator smh
      "@nrwl/workspace": { optional: true }

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
