logFilters:
  # discard skipped build script messages.
  # You think we'd know that since we went through the trouble explicitly disabling the package.
  - { code: YN0005, level: discard }

nodeLinker: node-modules

packageExtensions:
  "@nestjs/schematics@*":
    peerDependenciesMeta:
      typescript: { optional: true }
  "@nrwl/devkit@*":
    peerDependenciesMeta:
      nx: { optional: true }
  "@phenomnomnominal/tsquery@*":
    peerDependenciesMeta:
      # Not really, but it satisfies yarn the easiest and ofc we have typescript
      typescript: { optional: true }
  "ngx-deploy-npm@*":
    peerDependenciesMeta:
      # Only needed for init generator smh
      "@nrwl/workspace": { optional: true }
